import requests
from bs4 import BeautifulSoup
from feedgen.feed import FeedGenerator
import datetime

def scrape_website():
    url = 'https://www.csis.org/analysis'
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Example: Extract data you need (adjust selectors as necessary)
    data = []
    articles = soup.find_all('div', class_='teaser__content')
    for article in articles:
        title = article.find('h3', class_='teaser__title').get_text(strip=True)
        link = 'https://www.csis.org' + article.find('a')['href']
        description = article.find('div', class_='teaser__summary').get_text(strip=True)
        data.append({'title': title, 'link': link, 'description': description})
    
    return data

def generate_rss(data):
    fg = FeedGenerator()
    fg.title('CSIS Analysis RSS Feed')
    fg.link(href='https://www.csis.org/analysis', rel='alternate')
    fg.description('RSS feed generated by scraping the CSIS Analysis page')
    
    for item in data:
        fe = fg.add_entry()
        fe.title(item['title'])
        fe.link(href=item['link'])
        fe.description(item['description'])
        fe.pubDate(datetime.datetime.now())
    
    fg.rss_file('csis_analysis_feed.xml')

if __name__ == "__main__":
    scraped_data = scrape_website()
    generate_rss(scraped_data)